
# Setup
title:               Leoluyi 呂奕
tagline:             "Coding with Data"
description:         'My journey learning data science.'
permalink:           /:categories/:title
baseurl:             ""
url:                 https://leoluyi.tw
port: 4000
safe: false

# Build Settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
rdiscount:
  extensions: [smart]
# exclude:
#   - Gemfile
#   - Gemfile.lock

# Pagination
spaginate: 5
paginate: 5
paginate_path: '/blog/page/:num'
# pagination:
#   debug: true
#   collection: 'posts'
#   per_page: 5
#   permalink: '/page/:num/'

disqus: leoluyi
google_analytics: UA-515255-3

# About/contact
author:
  name: 呂奕 Leo - Lu Yi
  email: leo0650@gmail.com
  twitter: leo_luyi
  facebook: LeoYiLu
  linkedin: leoluyi
  github: leoluyi
  avatar: profile.jpg

# Custom vars
version:             1.0.0

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
