version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    environment:
        - JEKYLL_ENV=docker
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
    command: jekyll serve --watch --force_polling --verbose
